### ISSUE TITLE
PhotoMaker currently does not support multiple trigger words in a single prompt.

### ISSUE THREAD

**Issue by whq1rgb** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker-ZHO#56]
PhotoMaker currently does not support multiple trigger words in a single prompt. Trigger word: img, Prompt: food photography style 1.2, (head and shoulders portrait:1.5), (british woman 24-years-old:1.5), (blue eyes:1.25), (fearful, fearful expression:0.19), (heart-shaped shape face:0.16), (curtain bangs hairstyle:1.25), (brown hair:1.25), (disheveled:1.0), 1.2, (skin details, skin texture:0.16), (skin pores:0.16), (skin imperfections:0.3), (dimples:1.0), (freckles:0.19), (skin pores:0.5), (eyes details:0.41), (iris details:0.14), (circular iris:0.14), (circular pupil:0.13), (facial asymmetry, face asymmetry:0.14), 1.2, (detailed, professional photo, perfect exposition:1.25), (film grain:1.5) . appetizing, professional, culinary, high-resolution, commercial, highly detailed.

**Comment by start-life** [comment]
I have this problem too

**Comment by start-life** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO\PhotoMakerNode.py", line 396, in generate_image
    output = pipe(
             ^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO\pipeline.py", line 336, in __call__
    ) = self.encode_prompt_with_trigger_word(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO\pipeline.py", line 176, in encode_prompt_with_trigger_word
    raise ValueError(
ValueError: PhotoMaker currently does not support multiple trigger words in a single prompt.
Trigger word: img, Prompt: cinematic photo Muscular man in the gym . 35mm photograph, film, bokeh, professional, 4k, highly detailed.
